import React, { useEffect, useState } from 'react';
import { Lightbulb, RefreshCw, Filter, Sparkles, Briefcase, Layers } from 'lucide-react';
import TradeIdeaCard from '../features/trades/TradeIdeaCard';
import IdeaDetailModal from '../features/trades/IdeaDetailModal';
import PageHeader from '../components/layout/PageHeader';
import { api } from '../services/api/api.js';

const Ideas = () => {
  const [ideaList, setIdeaList] = useState([]);
  const [loading, setLoading] = useState(false);
  const [selectedIdea, setSelectedIdea] = useState(null);
  
  // STATE for View Mode: 'latest' or 'open'
  const [viewMode, setViewMode] = useState('latest');
  const [confidenceThreshold, setConfidenceThreshold] = useState(0);

  const fetchIdeas = async () => {
    setLoading(true);
    try {
      let res;
      
      // --- CONDITIONAL FETCHING BASED ON VIEW MODE ---
      if (viewMode === 'open') {
          res = await api.trades.getOpen();
          
          if (res.success && Array.isArray(res.data)) {
            // MAPPING: Extract nested idea and add trade info
            const mappedIdeas = res.data.map(trade => {
                const baseIdea = trade.idea || trade; 
                return {
                    ...baseIdea,
                    trade_id: trade.id, 
                    status: trade.status 
                };
            });
            setIdeaList(mappedIdeas);
          } else {
              setIdeaList([]);
          }

      } else {
          // Fetch Latest Ideas (Normal Flow)
          res = await api.tradeIdeas.getLatest(confidenceThreshold);
          if (res.success && Array.isArray(res.data)) {
            setIdeaList(res.data);
          }
      }

    } catch (error) {
      console.error("Failed to fetch ideas:", error);
      setIdeaList([]);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchIdeas();
  }, [confidenceThreshold, viewMode]); 

  const handleGenerate = async () => {
    setLoading(true);
    setViewMode('latest'); 
    try {
      await api.tradeIdeas.generate();
      setTimeout(fetchIdeas, 2000); 
    } catch (e) {
      setLoading(false);
    }
  };

  return (
    <div className="dash-page space-y-8">
      <PageHeader
        icon={Lightbulb}
        title={viewMode === 'open' ? 'Active Positions' : 'AI Trade Signals'}
        description={
          viewMode === 'open'
            ? 'Monitor and manage your currently open trades.'
            : 'Real-time setups generated by institutional AI models.'
        }
        action={
          <button
            type="button"
            onClick={handleGenerate}
            disabled={loading || viewMode === 'open'}
            className="btn-primary py-2.5 px-5 disabled:opacity-50"
          >
            {loading && viewMode === 'latest' ? <RefreshCw size={16} className="animate-spin" /> : <Sparkles size={16} />}
            Generate New Ideas
          </button>
        }
      />

      <div className="flex flex-wrap items-center gap-3 rounded-xl border border-border/60 bg-surface p-3">
         {/* VIEW MODE TOGGLE BUTTONS */}
         <div className="flex items-center bg-background rounded-md p-1 border border-border">
            <button 
              onClick={() => setViewMode('latest')}
              className={`px-3 py-1.5 text-xs font-bold rounded flex items-center gap-2 transition-all ${viewMode === 'latest' ? 'bg-primary text-white shadow' : 'text-text-muted hover:text-text-main'}`}
            >
              <Layers size={12}/> LATEST
            </button>
            <button 
              onClick={() => setViewMode('open')}
              className={`px-3 py-1.5 text-xs font-bold rounded flex items-center gap-2 transition-all ${viewMode === 'open' ? 'bg-surface-hover text-emerald-500 shadow-sm border-emerald-500/20' : 'text-text-muted hover:text-text-main'}`}
            >
              <Briefcase size={12}/> OPEN TRADES
            </button>
         </div>

         {/* Confidence Filter */}
         {viewMode === 'latest' && (
           <>
             <div className="w-px h-6 bg-border hidden md:block"></div>
             <div className="flex items-center gap-2 bg-background rounded-md p-1 border border-border">
                <Filter size={12} className="text-text-muted ml-2"/>
                <select 
                  value={confidenceThreshold}
                  onChange={(e) => setConfidenceThreshold(Number(e.target.value))}
                  className="bg-transparent text-xs font-bold text-text-main outline-none py-1 pr-2 cursor-pointer"
                >
                  <option value="0">All Confidence</option>
                  <option value="70">High Confidence (&gt;70%)</option>
                  <option value="85">Ultra High (&gt;85%)</option>
                </select>
             </div>
           </>
         )}

         <div className="flex-1 flex justify-end">
            <button 
              onClick={fetchIdeas} 
              className="p-1.5 text-text-muted hover:text-primary transition-colors rounded-full hover:bg-surface-hover"
              title="Refresh List"
            >
               <RefreshCw size={16} className={loading ? "animate-spin" : ""}/>
            </button>
         </div>
      </div>

      {/* IDEAS GRID */}
      {loading ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 opacity-50 pointer-events-none">
            {[1,2,3].map(i => <div key={i} className="h-[300px] bg-surface rounded-xl animate-pulse border border-border"></div>)}
          </div>
      ) : ideaList.length > 0 ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {ideaList.map((idea, idx) => (
            <TradeIdeaCard 
              key={idea.id || idx} 
              idea={idea} 
              onClick={() => setSelectedIdea(idea)}
              isOpenTrade={viewMode === 'open'}
            />
          ))}
        </div>
      ) : (
        <div className="text-center py-20 text-text-muted card-modern flex flex-col items-center">
           <Lightbulb size={48} className="mb-4 opacity-20" />
           <h3 className="font-bold text-lg">
             {viewMode === 'open' ? 'No active trades' : 'No trade ideas generated yet'}
           </h3>
           <p className="text-sm mt-2">
             {viewMode === 'open' ? 'Accept a trade idea to see it here.' : 'Click "Generate New Ideas" to get started.'}
           </p>
        </div>
      )}

      {/* DETAIL MODAL */}
      <IdeaDetailModal 
        isOpen={!!selectedIdea} 
        onClose={() => setSelectedIdea(null)} 
        idea={selectedIdea}
        initialTradeStatus={viewMode === 'open' ? 'active' : 'idle'}
      />
    </div>
  );
};

export default Ideas;